[package]
name = "dbg"
version = "0.1.0"
authors = ["Takumi Nishijo <hoge@hoge.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
# To make a DLL, enable this line and disable main.rs.
# To build main.rs, comment this out.

[dependencies]
libc = "0.2"
